# Generated by Django 2.2.6 on 2020-02-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200216_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('FIRST', '1st Semester'), ('SUMMER', 'Summer'), ('SECOND', '2nd Semeseter')], default='1st Semester', max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
