# Generated by Django 2.2.6 on 2020-06-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200226_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_answer', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'quiz_answer',
            },
        ),
        migrations.CreateModel(
            name='Quiz_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'quiz_choices',
            },
        ),
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('quiz_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Quiz_Answer')),
                ('quiz_choices', models.ManyToManyField(blank=True, to='app.Quiz_Choices')),
            ],
            options={
                'db_table': 'quiz_question',
            },
        ),
        migrations.CreateModel(
            name='Quiz_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(max_length=256, null=True)),
                ('instruction', models.CharField(blank=True, max_length=512, null=True)),
                ('points_per_item', models.IntegerField(null=True)),
                ('quiz_question', models.ManyToManyField(blank=True, to='app.Quiz_Question')),
            ],
            options={
                'db_table': 'quiz_section',
            },
        ),
        migrations.CreateModel(
            name='Quiz_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=256)),
                ('date', models.DateTimeField(null=True)),
                ('deadline', models.DateTimeField()),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Classroom')),
                ('quiz_section', models.ManyToManyField(blank=True, to='app.Quiz_Section')),
            ],
            options={
                'db_table': 'quiz_event',
            },
        ),
    ]
