# Generated by Django 2.2.6 on 2020-06-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_quiz_answer_quiz_choices_quiz_event_quiz_question_quiz_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('SECOND', '2nd Semeseter'), ('FIRST', '1st Semester'), ('SUMMER', 'Summer')], default='1st Semester', max_length=25),
        ),
    ]
