# Generated by Django 2.2.6 on 2020-06-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200601_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('SUMMER', 'Summer'), ('FIRST', '1st Semester'), ('SECOND', '2nd Semeseter')], default='1st Semester', max_length=25),
        ),
    ]
