# Generated by Django 2.2.6 on 2020-06-02 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200601_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('SECOND', '2nd Semeseter'), ('SUMMER', 'Summer'), ('FIRST', '1st Semester')], default='1st Semester', max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Account'),
        ),
    ]
