# Generated by Django 2.2.6 on 2020-06-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200602_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_question',
            name='question_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz_section',
            name='section_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('SUMMER', 'Summer'), ('FIRST', '1st Semester'), ('SECOND', '2nd Semeseter')], default='1st Semester', max_length=25),
        ),
    ]
