# Generated by Django 2.2.6 on 2020-06-09 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200608_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Quiz_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.CharField(max_length=255)),
                ('total_items', models.CharField(blank=True, max_length=255, null=True)),
                ('classroom', models.ManyToManyField(to='app.Classroom')),
                ('quiz_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Quiz_Event')),
                ('student', models.ManyToManyField(to='app.Student')),
            ],
        ),
    ]
