# Generated by Django 2.2.6 on 2020-06-13 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_student_quiz_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('SUMMER', 'Summer'), ('SECOND', '2nd Semeseter'), ('FIRST', '1st Semester')], default='1st Semester', max_length=25),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=32)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
            ],
        ),
    ]
