# Generated by Django 2.2.6 on 2020-06-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200613_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('SECOND', '2nd Semeseter'), ('FIRST', '1st Semester'), ('SUMMER', 'Summer')], default='1st Semester', max_length=25),
        ),
        migrations.CreateModel(
            name='Attendance_This_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.ManyToManyField(to='app.Attendance')),
            ],
        ),
    ]
