# Generated by Django 2.2.6 on 2020-06-13 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200613_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='classroom',
        ),
        migrations.AddField(
            model_name='attendance_this_day',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Classroom'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('FIRST', '1st Semester'), ('SECOND', '2nd Semeseter'), ('SUMMER', 'Summer')], default='1st Semester', max_length=25),
        ),
    ]
