# Generated by Django 2.2.6 on 2020-06-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200613_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('FIRST', '1st Semester'), ('SUMMER', 'Summer'), ('SECOND', '2nd Semeseter')], default='1st Semester', max_length=25),
        ),
        migrations.RemoveField(
            model_name='student_quiz_event',
            name='student',
        ),
        migrations.AddField(
            model_name='student_quiz_event',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
        ),
    ]
