# Generated by Django 2.2.6 on 2020-06-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200613_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='semester',
            field=models.CharField(choices=[('SUMMER', 'Summer'), ('SECOND', '2nd Semeseter'), ('FIRST', '1st Semester')], default='1st Semester', max_length=25),
        ),
        migrations.AlterField(
            model_name='login',
            name='verification_string',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
